---
apiVersion: v1
kind: Pod
metadata:
  name: fb-persists
spec:
  containers:
    - name: fb-persists
      image: fb-persists
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: fb-persists
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fb-persists
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/fb-persists/
  claimRef:
    name: fb-persists
    namespace: default

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fb-persists
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  volumeName: fb-persists
